[workspace]
members = [
    "absolut-core",
    "absolut-derive",
]

[package]
name = "absolut"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
quote = "1.0.31"
proc-macro2 = "1.0.66"

[dependencies]
absolut-core = { path = "absolut-core" }
absolut-derive = { path = "absolut-derive" }
