[workspace]
members = [
    "salut-core",
    "salut-derive",
]

[package]
name = "salut"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
quote = "1.0.31"
proc-macro2 = "1.0.66"

[dependencies]
salut-core = { path = "salut-core" }
salut-derive = { path = "salut-derive" }
