[package]
name = "salut-core"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }
z3 = { version = "0.11.2", features = ["static-link-z3"] }